spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    open-in-view: false
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1